import Vue from 'vue';

import EpAlert from './alert';
import EpBadge from './badge';
import EpBreadcrumb from './breadcrumb';
import EpBreadcrumbItem from './breadcrumb-item';
import EpButton from './button';
import EpButtonGroup from './buttonGroup';
import EpCheckbox from './checkbox';
import EpCheckboxGroup from './checkbox-group';
import EpCard from './card';
import EpCol from './col';
import EpForm from './form';
import EpFormItem from './form-item';
import EpInput from './input';
import EpInputNumber from './input-number';
import EpMessage from './message';
import EpMenu from './menu';
import EpMenuGroup from './menu-group';
import EpMenuItem from './menu-item';
import EpModel from './model';
import EpProgress from './progress';
import EpPagination from './pagination';
import EpRadio from './radio';
import EpRadioButton from './radio-button';
import EpRadioGroup from './radio-group';
import EpRow from './row';
import EpSelect from './select';
import EpStep from './step';
import EpSteps from './steps';
import EpSubmenu from './submenu';
import EpSwitch from './switch';
import EpTag from './tag';
import EpTable from './table';
import EpTableItem from './table-item';
import EpTabs from './tabs';
import EpTabItem from './tab-item';
import EpTime from './time';
import EpTransfer from './transfer';
import EpTooltip from './tooltip';

import "../src/directive";

Vue.component(EpAlert.name, EpAlert);
Vue.component(EpBadge.name, EpBadge);
Vue.component(EpBreadcrumb.name, EpBreadcrumb);
Vue.component(EpBreadcrumbItem.name, EpBreadcrumbItem);
Vue.component(EpButton.name, EpButton);
Vue.component(EpButtonGroup.name, EpButtonGroup);
Vue.component(EpCheckbox.name, EpCheckbox);
Vue.component(EpCheckboxGroup.name, EpCheckboxGroup);
Vue.component(EpCard.name, EpCard);
Vue.component(EpCol.name, EpCol);
Vue.component(EpForm.name, EpForm);
Vue.component(EpFormItem.name, EpFormItem);
Vue.component(EpInput.name, EpInput);
Vue.component(EpInputNumber.name, EpInputNumber);
Vue.component(EpMenu.name, EpMenu);
Vue.component(EpMenuGroup.name, EpMenuGroup);
Vue.component(EpMenuItem.name, EpMenuItem);
Vue.component(EpModel.name, EpModel);
Vue.component(EpProgress.name, EpProgress);
Vue.component(EpPagination.name, EpPagination);
Vue.component(EpRadio.name, EpRadio);
Vue.component(EpRadioButton.name, EpRadioButton);
Vue.component(EpRadioGroup.name, EpRadioGroup);
Vue.component(EpRow.name, EpRow);
Vue.component(EpSelect.name, EpSelect);
Vue.component(EpStep.name, EpStep);
Vue.component(EpSteps.name, EpSteps);
Vue.component(EpSubmenu.name, EpSubmenu);
Vue.component(EpSwitch.name, EpSwitch);
Vue.component(EpTag.name, EpTag);
Vue.component(EpTable.name, EpTable);
Vue.component(EpTableItem.name, EpTableItem);
Vue.component(EpTabs.name, EpTabs);
Vue.component(EpTabItem.name, EpTabItem);
Vue.component(EpTime.name, EpTime);
Vue.component(EpTransfer.name, EpTransfer);
Vue.component(EpTooltip.name, EpTooltip);

Vue.prototype.$pop = EpMessage;
